#!/bin/sh /etc/rc.common

START=75
USE_PROCD=1

MQTT_CONF=/etc/mosquitto/mosquitto-local.conf

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/mosquitto -c $MQTT_CONF
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param user mosquitto
	procd_set_param group mosquitto
	procd_set_param respawn 3600 200 0
	procd_set_param term_timeout 20
	procd_set_param nice -10
	procd_set_param no_new_privs 1
	procd_add_jail mosquitto-local
	procd_add_jail_mount $MQTT_CONF
	procd_add_jail_mount_rw /tmp
	procd_close_instance
}
