#!/bin/sh /etc/rc.common

START=85
USE_PROCD=1

readonly MQTT_AUTH='--unix /tmp/mosquitto.sock'
readonly SCRIPT=/usr/lib/rtl-433/ha-autodiscovery.sh

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/socat -U 
	procd_append_param command "EXEC:'/usr/bin/mosquitto_pub $MQTT_AUTH -V 5 -x 86400 --property publish message-expiry-interval 300 -l -t mqtt/publish',pipes"
	procd_append_param command EXEC:$SCRIPT,nofork,pipes
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param respawn 3600 15 0
	procd_set_param term_timeout 15
	procd_set_param nice 15
	procd_set_param user nobody
	procd_set_param group mosquitto
	procd_set_param no_new_privs 1
	procd_add_jail ha-autodiscovery
	procd_add_jail_mount /usr/bin/mosquitto_sub
	procd_add_jail_mount /usr/bin/mosquitto_pub
	procd_add_jail_mount /usr/bin/yq
	procd_add_jail_mount /usr/bin/find
	procd_add_jail_mount /usr/bin/basename
	procd_add_jail_mount /usr/bin/env
	procd_add_jail_mount $SCRIPT
	procd_add_jail_mount /usr/lib/rtl-433/ha-autodiscovery.yq
	procd_add_jail_mount /etc/home-assistant
	procd_add_jail_mount /tmp
	procd_add_jail_mount_rw /tmp/mosquitto.sock
	procd_close_instance
}
