#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

readonly MQTT_SOCKET=/tmp/mosquitto.sock
readonly SCRIPT=/usr/lib/rtl-433/mqtt-publisher.sh
readonly JQ_SCRIPT=/usr/lib/rtl-433/mqtt-publisher.jq

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/socat -u
	procd_append_param command "EXEC:'mosquitto_sub --unix $MQTT_SOCKET -V 5 -x 86400 -t mqtt/publish',pipes"
	procd_append_param command EXEC:$SCRIPT,nofork,pipes
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param respawn 3600 10 0
	procd_set_param term_timeout 10
	procd_set_param nice -5
	procd_set_param user nobody
	procd_set_param group mosquitto
	procd_set_param no_new_privs 1
	procd_add_jail mqtt-publisher
	procd_add_jail_mount /usr/bin/mosquitto_pub
	procd_add_jail_mount /usr/bin/mosquitto_sub
	procd_add_jail_mount /usr/bin/jq
	procd_add_jail_mount $SCRIPT
	procd_add_jail_mount $JQ_SCRIPT
	procd_add_jail_mount /tmp
	procd_add_jail_mount_rw $MQTT_SOCKET
	procd_close_instance
}
