#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

MQTT_SOCKET=/tmp/mosquitto.sock
JQ_SCRIPT=/usr/lib/rtl-433/rtl-433-processor.jq

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/socat
	procd_append_param command "EXEC:'mosquitto_sub --unix $MQTT_SOCKET -V 5 -t rtl_433/output/# -F %t\t%p',pipes!!EXEC:'mosquitto_pub --unix $MQTT_SOCKET -V 5 -x 86400 --property publish message-expiry-interval 300 -l -t mqtt/publish',pipes"
	procd_append_param command "EXEC:'jq --unbuffered -n -c -f $JQ_SCRIPT -R -S',pipes,nofork"
	procd_set_param stderr 1
	procd_set_param respawn 3600 10 0
	procd_set_param term_timeout 10
	procd_set_param nice -6
	procd_set_param user nobody
	procd_set_param group mosquitto
	procd_set_param no_new_privs 1
	procd_add_jail rtl-433-processor
	procd_add_jail_mount /usr/bin/mosquitto_pub
	procd_add_jail_mount /usr/bin/mosquitto_sub
	procd_add_jail_mount /usr/bin/jq
	procd_add_jail_mount $JQ_SCRIPT
	procd_add_jail_mount /tmp
	procd_add_jail_mount_rw $MQTT_SOCKET
	procd_close_instance
}
